// LOCALHOST 

### Get all contacts
GET http://localhost:8080/contacts 

### Get a contact by ID
GET http://localhost:8080/contacts/68200dc8ccd4551be1033338

### POST a new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Sarah",
  "lastName": "Lee",
  "email": "sarah@example.com",
  "favoriteColor": "Blue",
  "birthday": "05/06/2025"
}

### PUT update Sarah's contact
PUT http://localhost:8080/contacts/68200dc8ccd4551be1033338
Content-Type: application/json

{
  "email": "sarah.lee@example.com"
}

### DELETE contact by ID
DELETE http://localhost:8080/contacts/68200dc8ccd4551be1033338